export const match: string
export const alliance: string
export const red: string
export const blue: string
export const score: string
export const matchName: string
export const matchTime: string
export const navigation: string
export const navbar: string
export const icons: string
